### ISSUE TITLE
5 fold cross validation using verstack scsplit 

### ISSUE THREAD

**Issue by monajalal** [DanilZherebtsov/verstack#11]
Hi Danil,

Thanks a lot for your great package. I used this code:
```
x_train, x_val, y_train, y_val = scsplit(x, y, stratify = y, test_size=0.3, random_state=42)
train = [x_train, y_train] 
```

However, I am interested in doing a 5-fold cross validation. I was unsure how to use scsplit along with 5-fold CV method. Could you please share a code snippet that showcases this?

**Comment by DanilZherebtsov** [comment]
> Hi Danil,
> 
> Thanks a lot for your great package. I used this code:
> 
> ```
> x_train, x_val, y_train, y_val = scsplit(x, y, stratify = y, test_size=0.3, random_state=42)
> train = [x_train, y_train] 
> ```
> 
> However, I am interested in doing a 5-fold cross validation. I was unsure how to use scsplit along with 5-fold CV method. Could you please share a code snippet that showcases this?

Hi!
Although the verstack.stratified_continuous_split does not include a kfold option, I've drafted a workaround.

I've used the house prices dataset from Kaggle as an illustration of how to use scsplit with kfold.

This is arbitrary, but it works.

P.S. I've made 3 folds, but you can make 5, just make sure to create your first split (below) with test_size = 0.2 and increment the range in the latter for loop
```
from verstack.stratified_continuous_split import scsplit

# create first split
x_train, x_val, y_train, y_val = scsplit(x, y, stratify = y, test_size=0.3, random_state=42)

# save first split val indexes
first_val_ix = x_val.index.tolist()

# create a list where the used val indexes (that can not be used in subsequent val folds) will get appended
used_vals = first_val_ix.copy()

# create the maximum size for your subsequent val_folds
appropriate_val_size = len(first_val_ix)

# create dict to store your val indexes, populate it with first split val indexes
val_folds_ix_dict = {0:first_val_ix}

# create additional folds, make sure to increment the range if you need more folds
for fold in range(1,3):
    fold_val_ix = []
    
    while len(fold_val_ix) < appropriate_val_size:
        # remove the random_state setting
        X_train, X_val, Y_train, Y_val = scsplit(x, y, stratify = y, test_size=0.3)
        new_val_ix = list((set(X_val.index) - set(used_vals)))
        for i in new_val_ix:
            if len(fold_val_ix) < appropriate_val_size:
                fold_val_ix.append(i)
                used_vals.append(i)
            else:
                break

        val_folds_ix_dict[fold] = fold_val_ix
        print(f'Fold {fold} done')

# check the means of the folds you've created
for fold_num, fold_values in val_folds_ix_dict.items():
    val_ix = fold_values
    y_ix = list(y.index)
    train_ix = list(set(y_ix) - set(val_ix))
    print(f'fold: {fold_num}')
    print(f'val target mean  : {y[val_ix].mean()}')
    print(f'train target mean: {y[train_ix].mean()}')
    print('-'*25)
    
# your valid indexes broken up by folds are in val_folds_ix_dict
print(val_folds_ix_dict.keys())

```

**Comment by DanilZherebtsov** [comment]
@monajalal let me know if this solves your current problem

**Comment by monajalal** [comment]
Thanks a lot for your response, so I used the following and it keeps stuck in an infinite loop printing `Fold 4 done`

```
# create first split
x_train, x_val, y_train, y_val = scsplit(x, y, stratify = y, test_size=0.2, random_state=42)

# save first split val indexes
first_val_ix = x_val.index.tolist()

# create a list where the used val indexes (that can not be used in subsequent val folds) will get appended
used_vals = first_val_ix.copy()

# create the maximum size for your subsequent val_folds
appropriate_val_size = len(first_val_ix)

# create dict to store your val indexes, populate it with first split val indexes
val_folds_ix_dict = {0:first_val_ix}

# create additional folds, make sure to increment the range if you need more folds
for fold in range(1,5):
    fold_val_ix = []
    
    while len(fold_val_ix) < appropriate_val_size:
        # remove the random_state setting
        X_train, X_val, Y_train, Y_val = scsplit(x, y, stratify = y, test_size=0.2)
        new_val_ix = list((set(X_val.index) - set(used_vals)))
        for i in new_val_ix:
            if len(fold_val_ix) < appropriate_val_size:
                fold_val_ix.append(i)
                used_vals.append(i)
            else:
                break

        val_folds_ix_dict[fold] = fold_val_ix
        print(f'Fold {fold} done')

# check the means of the folds you've created
for fold_num, fold_values in val_folds_ix_dict.items():
    val_ix = fold_values
    y_ix = list(y.index)
    train_ix = list(set(y_ix) - set(val_ix))
    print(f'fold: {fold_num}')
    print(f'val target mean  : {y[val_ix].mean()}')
    print(f'train target mean: {y[train_ix].mean()}')
    print('-'*25)
    
# your valid indexes broken up by folds are in val_folds_ix_dict
print(val_folds_ix_dict.keys())


```

Also, is there a way to have train, test, val ration of 60/20/20 and at the same time 5-fold cross-validation? i think it's fine iif there are partial overlaps.

**Comment by monajalal** [comment]
I don't know if this would be valuable to know or not but when I do CTL+C keyboard interrupt, it shows that code is stuck here:

```
^CTraceback (most recent call last):
  File "5fold_stratified_train_test_val.py", line 52, in <module>
    X_train, X_val, Y_train, Y_val = scsplit(x, y, stratify = y, test_size=0.2)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/verstack/stratified_continuous_split.py", line 149, in scsplit
    y_binned = combine_single_valued_bins(y_binned)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/verstack/stratified_continuous_split.py", line 77, in combine_single_valued_bins
    nearest = find_nearest([x for x in y_binned if x not in keys_with_single_value], val)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/verstack/stratified_continuous_split.py", line 73, in find_nearest
    idx = (np.abs(array - value)).argmin()
KeyboardInterrupt
```

**Comment by monajalal** [comment]
Just to add that I want to combine the train, test, val split with stratified 5-fold cross validation (though I understand in this case only a split of 80-10-10 would work.

So, here is what works for 5-fold cross validation:

```
for j, train_test in enumerate(kf.split(x, y)):
  train_index, test_index = train_test
  x_train, x_val = x[train_index], x[test_index]
  y_train, y_val = y[train_index], y[test_index]

  train = [x_train, y_train]
  train_result = pd.concat(train, axis=1)

  train_numpy = train_result.to_numpy()
  np.random.shuffle(train_numpy)
  train_name = '../train_fold' + str(j+1) + '.txt'
  np.savetxt(train_name, train_numpy, fmt="%s", delimiter='\t')

  val = [x_val, y_val]
  val_result = pd.concat(val, axis=1)

  val_numpy = val_result.to_numpy()
  np.random.shuffle(val_numpy)
  val_name = '../val_fold' + str(j+1) + '.txt'
  np.savetxt(val_name, val_numpy, fmt="%s", delimiter='\t')
```

And here's the code that separately works for train, test, split in an stratified manner using your verstack package:
```
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y, test_size=0.4, random_state=42)
# reset indexes
x_test.reset_index(drop = True, inplace = True)
y_test.reset_index(drop = True, inplace = True)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, stratify=y, test_size=0.5, random_state=42) 
```
^ the code snippet has a bug and i create an issue for it separately.

So, how can I combine these two?

**Comment by DanilZherebtsov** [comment]
I've issued a fix for the stratified_continuous_split that should also affect your issue. https://github.com/DanilZherebtsov/verstack/issues/13#issuecomment-1282529218

if you could `$ pip install --upgrade verstack`, and try again.
