### ISSUE TITLE
train test val split of 60/20/20 doesn't work while it does using train_test_split from sklearn

### ISSUE THREAD

**Issue by monajalal** [DanilZherebtsov/verstack#13]
```
x_train, x_test, y_train, y_test = scsplit(x, y, stratify = y, test_size=0.4, random_state=42)
x_test, x_val, y_test, y_val = scsplit(x_test, y_test, stratify = y_test, test_size=0.5, random_state=42) 

```

^ doesn't work
```
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=42)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, test_size=0.5, random_state=42) 
```
^ works

```
Traceback (most recent call last):
  File "train_test_val.py", line 26, in <module>
    x_train, x_test, y_train, y_test = scsplit(x, y, stratify = y, test_size=0.4, random_state=42)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/verstack/stratified_continuous_split.py", line 153, in scsplit
    X_t, X_v, y_t, y_v = split(X, y_binned,
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2422, in train_test_split
    n_train, n_test = _validate_shuffle_split(
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2067, in _validate_shuffle_split
    raise ValueError(
ValueError: The sum of test_size and train_size = 1.1, should be in the (0, 1) range. Reduce test_size and/or train_size.
```

**Comment by DanilZherebtsov** [comment]
> 

Hi @monajalal 

Fixed the issue. Install the fresh version of `verstack`
`$ pip install --upgrade verstack`

And reset your indexes before doing the second split

```
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=42)
# reset indexes
x_test.reset_index(drop = True, inplace = True)
y_test.reset_index(drop = True, inplace = True)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, test_size=0.5, random_state=42) 
```

It does not reset indexes internally, because this is a sensitive issue. You might rely on your indexes so you decide wether you need to save original indexes or not before the split.

Let me know how it went.

**Comment by monajalal** [comment]
Thanks a lot for your response, so I used the following and it keeps stuck in an infinite loop printing `Fold 4 done`

```
# create first split
x_train, x_val, y_train, y_val = scsplit(x, y, stratify = y, test_size=0.2, random_state=42)

# save first split val indexes
first_val_ix = x_val.index.tolist()

# create a list where the used val indexes (that can not be used in subsequent val folds) will get appended
used_vals = first_val_ix.copy()

# create the maximum size for your subsequent val_folds
appropriate_val_size = len(first_val_ix)

# create dict to store your val indexes, populate it with first split val indexes
val_folds_ix_dict = {0:first_val_ix}

# create additional folds, make sure to increment the range if you need more folds
for fold in range(1,5):
    fold_val_ix = []
    
    while len(fold_val_ix) < appropriate_val_size:
        # remove the random_state setting
        X_train, X_val, Y_train, Y_val = scsplit(x, y, stratify = y, test_size=0.2)
        new_val_ix = list((set(X_val.index) - set(used_vals)))
        for i in new_val_ix:
            if len(fold_val_ix) < appropriate_val_size:
                fold_val_ix.append(i)
                used_vals.append(i)
            else:
                break

        val_folds_ix_dict[fold] = fold_val_ix
        print(f'Fold {fold} done')

# check the means of the folds you've created
for fold_num, fold_values in val_folds_ix_dict.items():
    val_ix = fold_values
    y_ix = list(y.index)
    train_ix = list(set(y_ix) - set(val_ix))
    print(f'fold: {fold_num}')
    print(f'val target mean  : {y[val_ix].mean()}')
    print(f'train target mean: {y[train_ix].mean()}')
    print('-'*25)
    
# your valid indexes broken up by folds are in val_folds_ix_dict
print(val_folds_ix_dict.keys())


```

Also, is there a way to have train, test, val ration of 60/20/20 and at the same time 5-fold cross validation? i think it's fine iif there are partial overlaps.

**Comment by monajalal** [comment]
Thanks a lot. Confirming that after upgrading the package, it worked correctly.

<img width="307" alt="Screen Shot 2021-12-10 at 4 20 58 PM" src="https://user-images.githubusercontent.com/1892917/145642861-6a664401-3f6e-4580-9933-8fbb0abef322.png">

**Comment by monajalal** [comment]
so, I just noticed that you had removed the stratify=y, and for me that is what causes the error.

So here's the code I have:
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y, test_size=0.4, random_state=42)
# reset indexes
x_test.reset_index(drop = True, inplace = True)
y_test.reset_index(drop = True, inplace = True)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, stratify=y_test, test_size=0.5, random_state=42) 

and here's the error:


```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_24143/1859206023.py in <module>
----> 1 x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y, test_size=0.4, random_state=42)
      2 # reset indexes
      3 x_test.reset_index(drop = True, inplace = True)
      4 y_test.reset_index(drop = True, inplace = True)
      5 x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, stratify=y_test, test_size=0.5, random_state=42)

/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/sklearn/model_selection/_split.py in train_test_split(test_size, train_size, random_state, shuffle, stratify, *arrays)
   2441         cv = CVClass(test_size=n_test, train_size=n_train, random_state=random_state)
   2442 
-> 2443         train, test = next(cv.split(X=arrays[0], y=stratify))
   2444 
   2445     return list(

/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/sklearn/model_selection/_split.py in split(self, X, y, groups)
   1598         """
   1599         X, y, groups = indexable(X, y, groups)
-> 1600         for train, test in self._iter_indices(X, y, groups):
   1601             yield train, test
   1602 

/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/sklearn/model_selection/_split.py in _iter_indices(self, X, y, groups)
   1938         class_counts = np.bincount(y_indices)
   1939         if np.min(class_counts) < 2:
-> 1940             raise ValueError(
   1941                 "The least populated class in y has only 1"
   1942                 " member, which is too few. The minimum"

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
```

**Comment by monajalal** [comment]
```
x_train, x_test, y_train, y_test = scsplit(x, y, stratify=y, test_size=0.4, random_state=42)
# reset indexes
x_test.reset_index(drop = True, inplace = True)
y_test.reset_index(drop = True, inplace = True)
x_test, x_val, y_test, y_val = scsplit(x_test, y_test, stratify=y_test, test_size=0.5, random_state=42) 
```

error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_24143/3064626340.py in <module>
      3 x_test.reset_index(drop = True, inplace = True)
      4 y_test.reset_index(drop = True, inplace = True)
----> 5 x_test, x_val, y_test, y_val = scsplit(x_test, y_test, stratify=y_test, test_size=0.5, random_state=42)

/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/verstack/stratified_continuous_split.py in scsplit(stratify, test_size, train_size, continuous, random_state, *args)
    166     y_binned = np.digitize(y, bins)
    167     # correct bins if necessary
--> 168     y_binned = combine_single_valued_bins(y_binned)
    169 
    170     # split

/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/verstack/stratified_continuous_split.py in combine_single_valued_bins(y_binned)
     59     # split neighbors into groups for combining
     60     splits = int(len(neighbors)/2)
---> 61     neighbors = np.array_split(neighbors, splits)
     62     for group in neighbors:
     63         val_to_use = group[0]

<__array_function__ internals> in array_split(*args, **kwargs)

/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/numpy/lib/shape_base.py in array_split(ary, indices_or_sections, axis)
    776         Nsections = int(indices_or_sections)
    777         if Nsections <= 0:
--> 778             raise ValueError('number sections must be larger than 0.') from None
    779         Neach_section, extras = divmod(Ntotal, Nsections)
    780         section_sizes = ([0] +

ValueError: number sections must be larger than 0.
```

**Comment by nelsmb** [comment]
Verstack 3.2.3 version.
Same error here
` *** ValueError: number sections must be larger than 0. `
I believe the problem is caused by the line 
` 174  y_binned = combine_single_valued_bins(y_binned) `
in the stratified_continuous_split.py
When there are no single valued bins the `combine_single_valued_bins` function runs anyway and then you get the above error. By looking my bins I found that there is no single valued bin so I commented out this function and it worked fine.
Hope I helped.

**Comment by DanilZherebtsov** [comment]
> Verstack 3.2.3 version.
> Same error here
> `*** ValueError: number sections must be larger than 0.`
> I believe the problem is caused by the line
> `174 y_binned = combine_single_valued_bins(y_binned)` in the stratified_continuous_split.py
> When there are no single valued bins the `combine_single_valued_bins` function runs anyway and then you get the above error. By looking my bins I found that there is no single valued bin so I commented out this function and it worked fine.
> Hope I helped.

Could you please provide a sample dataset and the code to reproduce this issue.
