### ISSUE TITLE
Staker

### ISSUE THREAD

**Issue by chrissny88** [DanilZherebtsov/verstack#26]
I trained stacker and every thing  went well but when I try to fit the final model with either layer_1_feats or both ,I get error
```
stacker = Stacker(objective = 'binary', auto = True)
X_train = stacker.fit_transform(X_train_un, y_train_un)
X_test = stacker.transform(X_test)

# get lists of features created in each layer
layer_1_feats = stacker.stacked_features['layer_1']
layer_2_feats = stacker.stacked_features['layer_2']

model = LogisticRegression(random_state=1)
```
`model.fit(X_train_un[layer_2_feats], y_train_un)`

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-126-9363d1839018>](https://localhost:8080/#) in <module>
----> 1 model.fit(X_train_un[layer_2_feats], y_train_un)

2 frames
[/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py](https://localhost:8080/#) in _validate_read_indexer(self, key, indexer, axis)
   1372                 if use_interval_msg:
   1373                     key = list(key)
-> 1374                 raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   1375 
   1376             not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())

KeyError: "None of [Index(['layer_2_0', 'layer_2_1', 'diff_layer_2_0_layer_2_1', 'layer_2_std',\n       'layer_2_mean'],\n      dtype='object')] are in the [columns]"
```

**Comment by DanilZherebtsov** [comment]
It appears that you are using a different version of your X (X_train_un).

Try `model.fit(X_train[layer_2_feats], y_train_un)`

**Comment by chrissny88** [comment]
Just corrected the error

```
stacker = Stacker(objective = 'binary', auto = True)
X_train_un = stacker.fit_transform(X_train_un, y_train_un)
X_test = stacker.transform(X_test)

# get lists of features created in each layer
layer_1_feats = stacker.stacked_features['layer_1']
layer_2_feats = stacker.stacked_features['layer_2']

model = LogisticRegression(random_state=1)
```
Now getting the below error when I run the code

```
.. fold 4 trained/predicted
     . Optimising model hyperparameters
     .. fold 2 trained/predicted
     .. fold 4 trained/predicted
     . Optimising model hyperparameters
     .. fold 2 trained/predicted
     .. fold 4 trained/predicted
     . Optimising model hyperparameters
     .. fold 2 trained/predicted
     .. fold 4 trained/predicted
     . Optimising model hyperparameters
     .. fold 2 trained/predicted
     .. fold 4 trained/predicted
     . Optimising model hyperparameters
     .. fold 2 trained/predicted
     .. fold 4 trained/predicted
     . Optimising model hyperparameters
     .. fold 2 trained/predicted
     .. fold 4 trained/predicted
     . Optimising model hyperparameters
     .. fold 2 trained/predicted
     .. fold 4 trained/predicted
     . Optimising model hyperparameters
     .. fold 2 trained/predicted
     .. fold 4 trained/predicted
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

14 frames
pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'diff_layer_1_0_layer_1_1'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
KeyError: 'diff_layer_1_0_layer_1_1'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<timed exec> in <module>

[/usr/local/lib/python3.8/dist-packages/pandas/core/internals/blocks.py](https://localhost:8080/#) in check_ndim(values, placement, ndim)
   1977             )
   1978         if len(placement) != len(values):
-> 1979             raise ValueError(
   1980                 f"Wrong number of items passed {len(values)}, "
   1981                 f"placement implies {len(placement)}"

ValueError: Wrong number of items passed 4, placement implies 1
```

**Comment by DanilZherebtsov** [comment]
Please share the data (if possible) and complete code snippet to generate the error.

**Comment by chrissny88** [comment]
I was able to trace the error and resolved it

**Comment by DanilZherebtsov** [comment]
So what was the problem? Stacker or internal?

**Comment by DanilZherebtsov** [comment]
Check out the new verstack module that just got released: https://danilzherebtsov.medium.com/automatic-memory-optimization-when-reading-data-into-pandas-a6000ed45896
Might come in handy for your project

**Comment by chrissny88** [comment]
I have a problem of not replicating the results.
Every time I run the code ,I get different results.

**Comment by chrissny88** [comment]
> Check out the new verstack module that just got released: https://danilzherebtsov.medium.com/automatic-memory-optimization-when-reading-data-into-pandas-a6000ed45896 Might come in handy for your project

This is cool stuff but I am getting error

```
ImportError                               Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 from verstack import PandasOptimizer
      2 opt = PandasOptimizer()

ImportError: cannot import name 'PandasOptimizer' from 'verstack' (C:\Users\hp\anaconda3\lib\site-packages\verstack\__init__.py)
```

**Comment by DanilZherebtsov** [comment]
Did you update `verstack`?

`pip install --upgrade verstack`

you should get version 3.6.0

**Comment by chrissny88** [comment]
after upgrading verstack

`opt = PandasOptimizer()`
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 opt = PandasOptimizer()

TypeError: 'module' object is not callable
```

**Comment by DanilZherebtsov** [comment]
I have tested on a few different machines/systems/users, everything is working as expected. Let me once again provide the pipeline which you should follow.

In terminal: `pip install --upgrade verstack`

In python:
```
import verstack
verstack.__version__
# the output should be 3.6.0

from verstack import PandasOptimizer
opt = PandasOptimizer()
df = opt.optimize_memory_usage('path_to_a_csv')
```

**Comment by chrissny88** [comment]
Tried again and now works well


```
 * Loading data with optimized dtypes...

   - Original data size: 3.22 MB

   - Optimized data size: 2.93 MB

   - Optimized data percentage of origianl data: 91.09%

 * Loading data with optimized dtypes...

   - Original data size: 3.22 MB

   - Optimized data size: 1.25 MB

   - Optimized data percentage of origianl data: 38.94%
```

It optimized well in the second dataset but not in the first one. What might be the cause?

**Comment by DanilZherebtsov** [comment]
The reason is simple. If your data has mostly numbers - their datatypes can be optimised, for example the int64 can be represented by int8 which will have an 8-fold memory decrease effect. Same goes for floats.

This cannot be done to the text data, so the more text data you have in your dataset - the less optimised it can be when you load it with PandasOptimizer. 

But this is not a problem because you will still have to represent your text data with numbers by applying some encoding, and after that is done, you can run PandasOptimizer on that dataset again directly (without having to save/load from disk) and all those new numeric fields will get optimised as well.

**Comment by chrissny88** [comment]
Noted.
Let's say I have encoded my dataset and now have X_train as dataset with only numeric values, is the following code the right way of optimizing it? 
`X_train = opt.optimize_memory_usage(X_train)`

**Comment by DanilZherebtsov** [comment]
Correct. It can optimise either a dataset while reading it from disk by batches (in case your dataset does not fit in memory at once) or it can optimise a pandas.DataFrame that is already in memory. So the code example that you shared will work just fine.

**Comment by chrissny88** [comment]
```
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\verstack\PandasOptimizer.py", line 279, in _optimize_df
    df = df.astype(self.optimized_dtypes)
  File "C:\Users\hp\anaconda3\lib\site-packages\pandas\core\generic.py", line 5879, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'Unnamed: 0' not found in columns."

! Columns names mismatch, initialize a fresh instance of PandasOptimizer
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [271], in <cell line: 1>()
----> 1 X_train = opt.optimize_memory_usage(X_train)

File ~\anaconda3\lib\site-packages\verstack\PandasOptimizer.py:324, in PandasOptimizer.optimize_memory_usage(self, path_or_df)
    322 if isinstance(path_or_df, pd.DataFrame):
    323     self.original_data_size_mb = sys.getsizeof(path_or_df)/1024/1024
--> 324     df = self._optimize_df(path_or_df)
    325     self._get_optimized_data_size_and_ratio(df)
    326     self._print_optimization_results()

File ~\anaconda3\lib\site-packages\verstack\PandasOptimizer.py:279, in PandasOptimizer._optimize_df(self, df)
    277 self._discover_chunk_dtypes(df)
    278 try:
--> 279     df = df.astype(self.optimized_dtypes)
    280 except KeyError as e:
    281     self.printer.print('Columns names mismatch, initialize a fresh instance of PandasOptimizer', order='error')

File ~\anaconda3\lib\site-packages\pandas\core\generic.py:5879, in NDFrame.astype(self, dtype, copy, errors)
   5877 for col_name in dtype.keys():
   5878     if col_name not in self:
-> 5879         raise KeyError(
   5880             "Only a column name can be used for the "
   5881             "key in a dtype mappings argument. "
   5882             f"'{col_name}' not found in columns."
   5883         )
   5885 # GH#44417 cast to Series so we can use .iat below, which will be
   5886 #  robust in case we
   5887 from pandas import Series

KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'Unnamed: 0' not found in columns."

``
Tried it and got the error`

**Comment by DanilZherebtsov** [comment]
That looks odd.

Could you please:
1. Share the columns names in your X_train
2. Try to initialise a fresh instance of PandasOptimizer before doing the `X_train = opt.optimize_memory_usage(X_train)`

**Comment by chrissny88** [comment]
```
Index(['health_center', 'enrollment_year', 'enrollment_quarter',
       'enrollment_day', 'age', 'number_of_programs',
       'days_taken_to_record_the_data', 'hospital_district_kayonza',
       'hospital_district_kirehe', 'enrollment_week_day_Monday',
       'enrollment_week_day_Saturday', 'enrollment_week_day_Sunday',
       'enrollment_week_day_Thursday', 'enrollment_week_day_Tuesday',
       'enrollment_week_day_Wednesday', 'gender_M', 'patient_district_kayonza',
       'patient_district_kirehe'],
      dtype='object')
```

**Comment by DanilZherebtsov** [comment]
can you try:
```
opt = PandasOptimizer()
X_train = opt.optimize_memory_usage(X_train)
```

**Comment by chrissny88** [comment]
> 
It worked. PandasOptimizer() is amazing, it considerably decreased the training time on a huge dataset I was working on.
Thanks

**Comment by DanilZherebtsov** [comment]
> It worked. PandasOptimizer() is amazing, it considerably decreased the training time on a huge dataset I was working on.
> Thanks

Great! What was the problem?

**Comment by chrissny88** [comment]
> > It worked. PandasOptimizer() is amazing, it considerably decreased the training time on a huge dataset I was working on.
> > Thanks
> 
> Great! What was the problem?

I did not define opt = PandasOptimizer() before

**Comment by chrissny88** [comment]
Can stacker handle missing values and categorical variables internally?

**Comment by DanilZherebtsov** [comment]
> Can stacker handle missing values and categorical variables internally?

No. You should deploy `verstack.NaNImputer` and any of the categoric encoders `verstack` has to offer prior to stacking
